---
- hosts: all
  vars_files:
   - vars.yml

  tasks:

    - name: git clone
      git:
        repo: 'https://github.com/AngieMP/my-first-blog.git'
        dest: "{{project_path}}"
        force: true
    
    - name: create venv and install requirements
      pip:
        requirements: "{{project_path}}/requirements.txt"
        virtualenv: "{{project_path}}/.venv"
    
    - name: give permissions 
      file:
        path: "{{project_path}}/manage.py"
        mode: 0777 # el modo que le da permisos de ejecución
        
    - name: makemigrations
      community.general.django_manage:
        command: makemigrations
        project_path: "{{project_path}}"
        virtual_env: "{{project_path}}/.venv"

    - name: migrate
      community.general.django_manage:
        command: migrate
        project_path: "{{project_path}}"
        virtual_env: "{{project_path}}/.venv"
    
    - name: load initial data
      django_manage: 
        command: loaddata
        project_path: "{{project_path}}"
        virtual_env: "{{project_path}}/.venv"
        fixtures: "{{project_path}}/db.json"
